ignore:
  - "tactics2d/dataset_parser/womd_proto"
  - "tactics2d/dataset_parser/parse_womd.py"
  - "tactics2d/dataset_parser/parse_nuplan.py"
  - "tactics2d/traffic/scenario_display.py"
  - "tactics2d/map/parser/fix_osm.py"
