# Check https://www.mkdocs.org/user-guide/configuration/
# for more MkDocs configuration details

site_name: Tactics2d-doc
# site_url: https://cybertorcs.readthedocs.io/zh_CN/latest/
site_description: The official documentation of Tactics2d.
site_author: WoodOxen
# repo_url: https://github.com/WoodOxen/CyberTorcs-doc

docs_dir: docs
nav:
  - Home: "index.md"
  - Install: "install.md"
  - Python_API: "python_api.md"

theme: "readthedocs"

plugins:
  - mkdocstrings:
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            heading_level: 2
            show_root_heading: true
  - search

markdown_extensions:
  - admonition
