# Check https://www.mkdocs.org/user-guide/configuration/
# for more MkDocs configuration details

site_name: Tactics2d-doc
site_url: https://tactics2d.readthedocs.io/en/latest/
site_description: The official documentation of Tactics2d.
site_author: WoodOxen
repo_url: https://github.com/WoodOxen/tactics2d

docs_dir: docs
nav:
  - Home: "index.md"
  - Install: "install.md"
  - Python API:
      - tactics2d.envs: "api_envs.md"
      - tactics2d.map: "api_map.md"
      - tactics2d.participant: "api_participant.md"
      - tactics2d.physics: "api_physics.md"
      - tactics2d.scenario: "api_scenario.md"
      - tactics2d.sensor: "api_sensor.md"
      - tactics2d.trajectory: "api_trajectory.md"

theme: "material"

plugins:
  - mkdocstrings:
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            heading_level: 1
            show_root_heading: true
  - search

markdown_extensions:
  - admonition
