name: Publish to Test PyPI
on:
  push:
    branches: release

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: recursive
      - name: Setup Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: /
          python -m pip install build --user
      - name: Build distribution
        run: /
          python -m build --sdist --wheel --outdir dist/
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
      