name: Tag on Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  tag_on_PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Tag on Pull Request
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
