name: Tag on Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  tag_on_PR:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag
        run: |
          git tag -a v0.1.3 -m "Version 0.1.3"
          git push origin v0.1.3
