name: Test Modules
on:
  - pull_request
  - workflow_dispatch

jobs:
  test-modules:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
          pip install bezier
      - name: Pytest
        run: |
          mkdir ./tests/runtime
          pytest tests --cov=tactics2d --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
  
  test-modules-on-Ubuntu1804:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive
      - name: Start docker environment
        run: |
          docker pull ubuntu:18.04
          docker run -it -v $PWD/tactics2d:/tactics2d ubuntu:18.04
      - name: Setup Python ${{ matrix.python-version }}
        run: |
          apt-get update
          apt-get install -y python${{ matrix.python-version }}
          apt-get install -y python${{ matrix.python-version }}-pip
          python3.7 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
          python3.7 -m pip install bezier
      - name: Pytest
        run: |
          cd /tactics2d
          mkdir ./tests/runtime
          pytest tests --cov=tactics2d --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3